services:
  - type: web
    name: aimmy-v2-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: CONFIDENCE_THRESHOLD
        value: "0.5"
      - key: DETECTION_INTERVAL
        value: "50"
      - key: ENABLE_ESP
        value: "true"
      - key: ENABLE_DEBUG_MODE
        value: "true"
